# src/main/resources/application-dev.yml
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: ERROR
    com.pakal.cloud: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---