# src/main/resources/application.yml
server:
  port: 8083

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/blogdb}
  application:
    name: blog-form-api

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics